### ISSUE TITLE
FR_DISK_ERR happen

### ISSUE THREAD

**Issue by warmc** [kiwih/cubemx-mmc-sd-card#1]
i found the switch in ( user_diskio_spi.c -> USER_SPI_ioctl() ) do not have "case GET_SECTOR_SIZE"
and  f_mount return FR_DISK_ERR.
please help, thanks.

**Comment by kiwih** [comment]
Unfortunately this code was written some time ago for an older version of CubeMX. It's possible an update somewhere along the line has broken things and I no longer have the hardware to test it against - sorry!

**Comment by KaushalBhattBharuch** [comment]
@warmc  add following case to switch you mentioned it works fine

`case GET_SECTOR_SIZE:
		*(WORD*) buff = 512;
		res = RES_OK;
		break;`
